### PR TITLE
[WIP] Feature/sessions with gc

### LINKED ISSUE #31: Built-in Memory session leaks?
Loading a simple `c.Session()` (not even a get/set on it) on the `context` and then running `wrk -d10s -t3 -c100 https://localhost:8443` benchmark spikes my initial app's 50MB memory instantly to `450MB+`. Turning the session-access off on a test page in my application and the whole overhead is instantly gone and even after running multiple runs the memory stays super steady the same low usage.

Is this virtual growth or really a bug? I'm using github.com/gorilla/securecookie as the encoder/decoder, but even if I just use native unmodified built-in memory session storage it keeps on leaking. Every re-run on the same process just add another 350~450MB to the process' memory usage.

This was a note I already had on my list for a long time using Iris, but as the benchmark will never be a use-case in my situation (yet) I kind of postponed it. I hope maybe we can look at this together and figure out what causes this and if the concern should be valid.

### PR DESCRIPTION
**Pull request by Dexus**
*   **Please check if the PR fulfills these requirements**

*   The commit message follows our guidelines. See [Contributing guide](https://github.com/go-siris/siris/blob/master/CONTRIBUTING.MD)
*   Tests for the changes have been added (for bug fixes / features)
    - [x] Yes
*   Docs have been added / updated (for bug fixes / features)
    - [x] Yes

*   **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix and feature

*   **What is the current behavior?** (You can also link to an open issue here)
#31 

*   **What is the new behavior (if this is a feature change)?**
Sessions with a correct Grabage Collector (GC) to free memory of old sessions.

*   **Does this PR introduce a breaking change?** 
Yes, the SessionManager is now a other.

*   **Other information**:
_**Includes also a vendor update**_
close #31

### CODE REVIEW

**Review by statusdevel — CHANGES_REQUESTED** [review]
See #48

**Comment by theodesp** [comment]
Hey I just found that article comparing Badger Vs BoldDB
https://medium.com/@hendra_zhong/badger-vs-boltdb-persistent-key-value-store-written-in-go-e94ada87048f

Maybe we can add a plugin for interfacing Badger as a session store

**Review by godofdream — APPROVED** [review]
I didn't find new bugs. We don't break any licenses. Seems ok.

**Review by Allendar — APPROVED** [review]
LGTM :)

**Comment by Dexus** [comment]
> @theodesp 
>Hey I just found that article comparing Badger Vs BoldDB
>https://medium.com/@hendra_zhong/badger-vs-boltdb-persistent-key-value-store-written-in-go-e94ada87048f
>
>Maybe we can add a plugin for interfacing Badger as a session store

I will create a new PR for that backend.

**Pull request merged**
